# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # 1. Do an apt upgrade and install prerequisites for ansible
  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      export DEB_FRONTEND=noninteractive
      apt-get update -y
      apt-get dist-upgrade -y
      apt-get install -y lvm2 python2.7-minimal python-minimal python-apt debconf debconf-utils
    SHELL
  end

  config.vm.hostname = "ansible-debootstrap"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "ansible-debootstrap"

    tgtdisk = ".vagrant/dbserver_sdc.vmdk"
    if !File.exist?(tgtdisk)
      vb.customize ['createhd', '--filename', tgtdisk, '--variant', 'Fixed', '--size', 20 * 1024]
    end
    vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', tgtdisk]
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end

  # Forward an additional ssh port 2223
  config.vm.network "forwarded_port", guest: 2222, host: 22222, host_ip: "127.0.0.1"

  config.ssh.forward_agent = true
  config.ssh.insert_key = true
  # config.ssh.keys_only = false

end
