---

- block:
  - name: Install dependencies on host
    apt:
      name: "{{ dependencies.md }}"
      state: present
      update_cache: no

  - name: Be sure to install mdadm in target
    set_fact:
      install_packages: "{{ install_packages + dependencies.md }}"

  when: md|count > 0

# @TODO: assumes a host system without RAID, better to determine the next free md device programmatically
# Ubuntu has the habit of renaming devices with a raid name to md127, md126 etc.
- name: create MD devices
  command: >
    mdadm --create /dev/md{{ 127 - device_num }} --level {{ device.level }} --raid-devices {{ device.members|count }}
    {% if device.level != 0 %}--bitmap=internal{% endif %} --name {{ device.name }} --metadata 1.2
    {% if 'chunk_size' in device %}--chunk {{ device.chunk_size }}{% endif %} {{ device.members|join(" ") }}
  loop_control:
    index_var: device_num
    loop_var: device
  loop: "{{ md }}"

- name: add md to tgt devices
  set_fact:
    _tgt_devices: >
        {{ _tgt_devices|combine({"/dev/md" + (127 - device_num)|string: device}) }}
  loop_control:
    index_var: device_num
    loop_var: device
  loop: "{{ md }}"

- debug:
    var: _tgt_devices
    verbosity: 2